# Generated by Django 2.1.1 on 2018-09-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
